// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v3.20.3
// source: jwt-protobuf/protos/jwt.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JWTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JWTRequest) Reset() {
	*x = JWTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_protobuf_protos_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTRequest) ProtoMessage() {}

func (x *JWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_protobuf_protos_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTRequest.ProtoReflect.Descriptor instead.
func (*JWTRequest) Descriptor() ([]byte, []int) {
	return file_jwt_protobuf_protos_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *JWTRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JWTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JWTResponse) Reset() {
	*x = JWTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwt_protobuf_protos_jwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTResponse) ProtoMessage() {}

func (x *JWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_protobuf_protos_jwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTResponse.ProtoReflect.Descriptor instead.
func (*JWTResponse) Descriptor() ([]byte, []int) {
	return file_jwt_protobuf_protos_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *JWTResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_jwt_protobuf_protos_jwt_proto protoreflect.FileDescriptor

var file_jwt_protobuf_protos_jwt_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6a, 0x77, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x1c, 0x0a, 0x0a, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x0b, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x3d, 0x0a, 0x0a, 0x4a, 0x57, 0x54, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4a, 0x57, 0x54, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwt_protobuf_protos_jwt_proto_rawDescOnce sync.Once
	file_jwt_protobuf_protos_jwt_proto_rawDescData = file_jwt_protobuf_protos_jwt_proto_rawDesc
)

func file_jwt_protobuf_protos_jwt_proto_rawDescGZIP() []byte {
	file_jwt_protobuf_protos_jwt_proto_rawDescOnce.Do(func() {
		file_jwt_protobuf_protos_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwt_protobuf_protos_jwt_proto_rawDescData)
	})
	return file_jwt_protobuf_protos_jwt_proto_rawDescData
}

var file_jwt_protobuf_protos_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jwt_protobuf_protos_jwt_proto_goTypes = []interface{}{
	(*JWTRequest)(nil),  // 0: main.JWTRequest
	(*JWTResponse)(nil), // 1: main.JWTResponse
}
var file_jwt_protobuf_protos_jwt_proto_depIdxs = []int32{
	0, // 0: main.JWTService.GetToken:input_type -> main.JWTRequest
	1, // 1: main.JWTService.GetToken:output_type -> main.JWTResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwt_protobuf_protos_jwt_proto_init() }
func file_jwt_protobuf_protos_jwt_proto_init() {
	if File_jwt_protobuf_protos_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwt_protobuf_protos_jwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwt_protobuf_protos_jwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwt_protobuf_protos_jwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwt_protobuf_protos_jwt_proto_goTypes,
		DependencyIndexes: file_jwt_protobuf_protos_jwt_proto_depIdxs,
		MessageInfos:      file_jwt_protobuf_protos_jwt_proto_msgTypes,
	}.Build()
	File_jwt_protobuf_protos_jwt_proto = out.File
	file_jwt_protobuf_protos_jwt_proto_rawDesc = nil
	file_jwt_protobuf_protos_jwt_proto_goTypes = nil
	file_jwt_protobuf_protos_jwt_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JWTServiceClient is the client API for JWTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JWTServiceClient interface {
	GetToken(ctx context.Context, in *JWTRequest, opts ...grpc.CallOption) (*JWTResponse, error)
}

type jWTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJWTServiceClient(cc grpc.ClientConnInterface) JWTServiceClient {
	return &jWTServiceClient{cc}
}

func (c *jWTServiceClient) GetToken(ctx context.Context, in *JWTRequest, opts ...grpc.CallOption) (*JWTResponse, error) {
	out := new(JWTResponse)
	err := c.cc.Invoke(ctx, "/main.JWTService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTServiceServer is the server API for JWTService service.
type JWTServiceServer interface {
	GetToken(context.Context, *JWTRequest) (*JWTResponse, error)
}

// UnimplementedJWTServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJWTServiceServer struct {
}

func (*UnimplementedJWTServiceServer) GetToken(context.Context, *JWTRequest) (*JWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}

func RegisterJWTServiceServer(s *grpc.Server, srv JWTServiceServer) {
	s.RegisterService(&_JWTService_serviceDesc, srv)
}

func _JWTService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.JWTService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServiceServer).GetToken(ctx, req.(*JWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWTService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.JWTService",
	HandlerType: (*JWTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _JWTService_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt-protobuf/protos/jwt.proto",
}
